<?php

namespace App\Constants;

class Industries {
    public const Industries = [
        'Agriculture',
        'Forestry',
        'Fishing',
        'Mining & Quarrying',
        'Oil & Gas Extraction',
        'Manufacturing',
        'Automobiles',
        'Food & Beverages',
        'Textiles & Apparel',
        'Electronics & Appliances',
        'Chemicals & Pharmaceuticals',
        'Metal & Steel',
        'Paper & Packaging',
        'Furniture & Wood Products',
        'Construction',
        'Residential Construction',
        'Commercial Construction',
        'Infrastructure',
        'Energy Production',
        'Electricity Generation',
        'Renewable Energy',
        'Nuclear Energy',
        'Coal and Fossil Fuels',
        'Retail',
        'Wholesale Trade',
        'Transportation & Logistics',
        'Banking & Financial Services',
        'Insurance',
        'Real Estate & Property Management',
        'Healthcare & Social Services',
        'Education',
        'Tourism & Hospitality',
        'Entertainment & Media',
        'Information Technology',
        'Telecommunications',
        'Legal Services',
        'Professional Services',
        'Research & Development',
        'Financial Analysis & Management',
        'Design & Creative Services',
        'Intellectual Property & Patent Services',
        'Government & Public Administration',
        'Non-Profit Organizations',
        'Scientific Research & Innovation',
        'Art & Culture',
        'Philanthropy & Social Work',
        'Aerospace & Defense',
        'Automotive',
        'Biotechnology',
        'Blockchain & Cryptocurrency',
        'E-commerce',
        'Cybersecurity',
        'Sports & Recreation',
        'Space Exploration & Technology',
        'Food & Beverage Services',
        'Fashion & Apparel'
    ];
}
