<?php

namespace App\Constants;

class Industries {
    public const Industries = [
        'Agriculture',
        'Forestry',
        'Fishing',
        'Mining & Quarrying',
        'Oil & Gas Extraction',
        'Manufacturing',
        'Automobiles',
        'Food & Beverages',
        'Textiles & Apparel',
        'Electronics & Appliances',
        'Chemicals & Pharmaceuticals',
        'Metal & Steel',
        'Paper & Packaging',
        'Furniture & Wood Products',
        'Construction',
        'Residential Construction',
        'Commercial Construction',
        'Infrastructure',
        'Energy Production',
        'Electricity Generation',
        'Renewable Energy',
        'Nuclear Energy',
        'Coal and Fossil Fuels',
        'Retail',
        'Wholesale Trade',
        'Transportation & Logistics',
        'Banking & Financial Services',
        'Insurance',
        'Real Estate & Property Management',
        'Healthcare & Social Services',
        'Education',
        'Tourism & Hospitality',
        'Entertainment & Media',
        'Information Technology',
        'Telecommunications',
        'Legal Services',
        'Professional Services',
        'Research & Development',
        'Financial Analysis & Management',
        'Design & Creative Services',
        'Intellectual Property & Patent Services',
        'Government & Public Administration',
        'Non-Profit Organizations',
        'Scientific Research & Innovation',
        'Art & Culture',
        'Philanthropy & Social Work',
        'Aerospace & Defense',
        'Automotive',
        'Biotechnology',
        'Blockchain & Cryptocurrency',
        'E-commerce',
        'Cybersecurity',
        'Sports & Recreation',
        'Space Exploration & Technology',
        'Food & Beverage Services',
        'Fashion & Apparel'
    ];

    public const INDUSTRIES_KV = [
        'Agriculture' => 'Agriculture',
        'Forestry' => 'Forestry',
        'Fishing' => 'Fishing',
        'Mining & Quarrying' => 'Mining & Quarrying',
        'Oil & Gas Extraction' => 'Oil & Gas Extraction',
        'Manufacturing' => 'Manufacturing',
        'Automobiles' => 'Automobiles',
        'Food & Beverages' => 'Food & Beverages',
        'Textiles & Apparel' => 'Textiles & Apparel',
        'Electronics & Appliances' => 'Electronics & Appliances',
        'Chemicals & Pharmaceuticals' => 'Chemicals & Pharmaceuticals',
        'Metal & Steel' => 'Metal & Steel',
        'Paper & Packaging' => 'Paper & Packaging',
        'Furniture & Wood Products' => 'Furniture & Wood Products',
        'Construction' => 'Construction',
        'Residential Construction' => 'Residential Construction',
        'Commercial Construction' => 'Commercial Construction',
        'Infrastructure' => 'Infrastructure',
        'Energy Production' => 'Energy Production',
        'Electricity Generation' => 'Electricity Generation',
        'Renewable Energy' => 'Renewable Energy',
        'Nuclear Energy' => 'Nuclear Energy',
        'Coal and Fossil Fuels' => 'Coal and Fossil Fuels',
        'Retail' => 'Retail',
        'Wholesale Trade' => 'Wholesale Trade',
        'Transportation & Logistics' => 'Transportation & Logistics',
        'Banking & Financial Services' => 'Banking & Financial Services',
        'Insurance' => 'Insurance',
        'Real Estate & Property Management' => 'Real Estate & Property Management',
        'Healthcare & Social Services' => 'Healthcare & Social Services',
        'Education' => 'Education',
        'Tourism & Hospitality' => 'Tourism & Hospitality',
        'Entertainment & Media' => 'Entertainment & Media',
        'Information Technology' => 'Information Technology',
        'Telecommunications' => 'Telecommunications',
        'Legal Services' => 'Legal Services',
        'Professional Services' => 'Professional Services',
        'Research & Development' => 'Research & Development',
        'Financial Analysis & Management' => 'Financial Analysis & Management',
        'Design & Creative Services' => 'Design & Creative Services',
        'Intellectual Property & Patent Services' => 'Intellectual Property & Patent Services',
        'Government & Public Administration' => 'Government & Public Administration',
        'Non-Profit Organizations' => 'Non-Profit Organizations',
        'Scientific Research & Innovation' => 'Scientific Research & Innovation',
        'Art & Culture' => 'Art & Culture',
        'Philanthropy & Social Work' => 'Philanthropy & Social Work',
        'Aerospace & Defense' => 'Aerospace & Defense',
        'Automotive' => 'Automotive',
        'Biotechnology' => 'Biotechnology',
        'Blockchain & Cryptocurrency' => 'Blockchain & Cryptocurrency',
        'E-commerce' => 'E-commerce',
        'Cybersecurity' => 'Cybersecurity',
        'Sports & Recreation' => 'Sports & Recreation',
        'Space Exploration & Technology' => 'Space Exploration & Technology',
        'Food & Beverage Services' => 'Food & Beverage Services',
        'Fashion & Apparel' => 'Fashion & Apparel',
    ];
}
