export const BUSINESS_MODELS: string[] = [
    "Advertising",
    "Affiliate",
    "Brokerage",
    "Concierge/Customization",
    "Crowdsourcing",
    "Disintermediation",
    "Fractionalization",
    "Franchise",
    "Freemium",
    "Leasing",
    "Lowtouch",
    "Marketplace",
    "Pay-as-you-go",
    "Razor blade",
    "Reverse razor blade",
    "Reverse auction",
    "Subscription",
    "Access to excess",
    "Blockchain",
] as const;

export const INDUSTRIES: string[] = [
    "Agriculture",
    "Aerospace & Defense",
    "Art & Culture",
    "Automobiles",
    "Automotive",
    "Banking & Financial Services",
    "Biotechnology",
    "Blockchain & Cryptocurrency",
    "Chemicals & Pharmaceuticals",
    "Commercial Construction",
    "Construction",
    "Cybersecurity",
    "Design & Creative Services",
    "Electronics & Appliances",
    "Energy Production",
    "Electricity Generation",
    "E-commerce",
    "Entertainment & Media",
    "Fashion & Apparel",
    "Financial Analysis & Management",
    "Fishing",
    "Food & Beverage Services",
    "Food & Beverages",
    "Forestry",
    "Furniture & Wood Products",
    "Government & Public Administration",
    "Healthcare & Social Services",
    "Information Technology",
    "Infrastructure",
    "Insurance",
    "Intellectual Property & Patent Services",
    "Legal Services",
    "Manufacturing",
    "Metal & Steel",
    "Mining & Quarrying",
    "Non-Profit Organizations",
    "Nuclear Energy",
    "Oil & Gas Extraction",
    "Paper & Packaging",
    "Philanthropy & Social Work",
    "Professional Services",
    "Real Estate & Property Management",
    "Renewable Energy",
    "Research & Development",
    "Residential Construction",
    "Retail",
    "Scientific Research & Innovation",
    "Space Exploration & Technology",
    "Sports & Recreation",
    "Telecommunications",
    "Textiles & Apparel",
    "Tourism & Hospitality",
    "Transportation & Logistics",
    "Wholesale Trade",
] as const;
